from typing import List, Dict
from dataclasses import dataclass
from .Items import base_id

@dataclass
class JILocation:
    name: str
    id : int

location_list : List[JILocation] = [
JILocation('Upgrade Bot 0',base_id+0),
JILocation('Upgrade Bot 1',base_id+1),
JILocation('Upgrade Bot 2',base_id+2),
JILocation('Upgrade Bot 3',base_id+3),
JILocation('Upgrade Bot 4',base_id+4),
JILocation('Upgrade Bot 5',base_id+5),
JILocation('Upgrade Bot 6',base_id+6),
JILocation('Upgrade Bot 7',base_id+7),
JILocation('Upgrade Bot 8',base_id+8),
JILocation('Upgrade Bot 9',base_id+9),
JILocation('Upgrade Bot 10',base_id+0),
JILocation('Upgrade Bot 11',base_id+1),
JILocation('Upgrade Bot 12',base_id+2),
JILocation('Upgrade Bot 13',base_id+3),
JILocation('Upgrade Bot 14',base_id+4),
JILocation('Upgrade Bot 15',base_id+5),
JILocation('Upgrade Bot 16',base_id+6),
JILocation('Upgrade Bot 17',base_id+7),
JILocation('Upgrade Bot 18',base_id+8),
JILocation('Upgrade Bot 19',base_id+9),
JILocation('Modifier Extreme Rotation',base_id+20),
JILocation('Modifier Slowmo Hookshots',base_id+21),
JILocation('Modifier Mars Gravity',base_id+22),
JILocation('Modifier Falling Up',base_id+23),
JILocation('Modifier Jets Only',base_id+24),
JILocation('Modifier Upsidedown World',base_id+25),
JILocation('Modifier Jupiter Gravity',base_id+26),
JILocation('Modifier Hookshots Only',base_id+27),
JILocation('Modifier Sideways World',base_id+28),
JILocation('Modifier Sun Gravity',base_id+29),
JILocation('Modifier Super Explosions',base_id+30),
JILocation('Modifier Zero Gravity',base_id+31),
JILocation('Modifier Too Much Jets',base_id+32),
JILocation('Modifier Moon Gravity',base_id+33),
JILocation('Modifier Infinite Jets',base_id+34),
JILocation('Modifier Super Hookshots',base_id+35),
JILocation('Modifier Random World Rot On Respawn',base_id+36),
JILocation('Modifier Multiple Modifiers',base_id+37),
JILocation('Modifier TenX Speed',base_id+38),
JILocation('Modifier Backwards Jets',base_id+39),
JILocation('Modifier Stretchy Hookshots',base_id+40),
JILocation('Modifier Hookshots Are Stilts',base_id+41),
JILocation('Modifier Bouncy Ground',base_id+42),
JILocation('Modifier Ground Is Lava',base_id+43),
JILocation('Modifier Gun Only',base_id+44),
JILocation('Modifier Gun Always Charged',base_id+45),
JILocation('Modifier Gun Rapid Fire',base_id+46),
JILocation('Modifier Night Sky',base_id+47),
JILocation('Modifier Pitch Black',base_id+48),
JILocation('Modifier Foggy',base_id+49),
JILocation('Modifier Death On Hard Impact',base_id+50),
JILocation('Modifier Palm Jets',base_id+51),
JILocation('Modifier Delicate Player',base_id+52),
JILocation('Modifier Super Wormy',base_id+53),
JILocation('MiniBoss 1 Killed',base_id+54),
JILocation('MiniBoss 2 Killed',base_id+55),
JILocation('MiniBoss 3 Killed',base_id+56),
JILocation('MiniBoss 4 Killed',base_id+57),
JILocation('Boss Killed',base_id+58),
]